services:

  postgres:
    image: postgres
    restart: no
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080
